name: GSForge
channels:
  - conda-forge
dependencies:
  - python=3.7
  - boruta_py
  - bokeh
  - click
  - datashader
  - h5py
  - holoviews
  - jupyter
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - panel
  - param
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - umap-learn
  - pip
  - pip:
      - methodtools
      - git+https://github.com/SystemsGenetics/GSForge
